# 博客地址
baseURL = "http://blog.yitinglove.cn/"

# 语言
languageCode = "zh_CN"

# 博客标题
title = "夜来卧听风吹雨,铁马冰河入梦来"

publishDir = "docs"
contentDir = "content"
layoutDir = "layouts"
buildDrafts = false
canonifyURLs = true

themesDir = "themes"
theme = "casper"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    author = "chengyi"


