# 博客地址
baseURL = "http://blog.yitinglove.cn/"

# 语言
languageCode = "zh_CN"

# 博客标题
title = "道法自然"

# 格式
# 每页记录数
paginate = 5

# Directory
publishDir = "docs"
contentDir = "content"
layoutDir = "layouts"
themesDir = "themes"

# 其他
buildDrafts = false
canonifyurls = true
hjsStyle = "default"

# 主题 cactus
theme = "casper"

# 评论
DisqusShortname = "blog-yitinglove-cn"

[params]
    description = "闻之我也野，视之我也饶，行之我也明"
    author = "成祎"
    authorlocation = "Shanghai, China"
    authorwebsite = "blog.yitinglove.cn"
    bio = "系统开发工程师"
    # 作者图片
    logo = "images/author.jpg"
    # 封面图片
    cover = "images/cover.jpg"
    googleAnalyticsUserID = "UA-72539373-3"
    githubName = "chengyi818"
    hideHUGOSupport = false

# 右侧菜单
[[menu.main]] #页面菜单参数
  name = "Home"
  weight = -120
  identifier = "blog"
  url = "/"
